Renamed the di service endpoints
CDCgov/NEDSS-DataIngestion pull request #164
Opened 2024-05-15 15:45 UTC by ssathiah

Renamed the DI service endpoints and removed the unused endpoints.

2024-05-15 17:01 UTC, ndduc01 approved these changes

2024-05-16 18:38 UTC, rshanmugam-enquizit requested changes

2024-05-16 18:38 UTC, rshanmugam-enquizit commented on data-ingestion-service/src/main/java/gov/cdc/dataingestion/deadletter/controller/ElrDeadLetterController.java
> +    @PostMapping(consumes = MediaType.TEXT_PLAIN_VALUE, path = "/reprocess-dlt-message")
you can say `reinject` here instead of `reprocess`

2024-05-23 17:38 UTC, rshanmugam-enquizit approved these changes
lgtm!

2024-05-24 19:35 UTC, merged