Update the DI Data Definition Language Scripts
CDCgov/NEDSS-DataIngestion pull request #90
Opened 2023-11-02 17:28 UTC by alog-enquizit

Update DI DDL scripts to include the Database creation and selectively create tables only if they are absent.

2023-11-02 17:29 UTC, alog-enquizit commented on report-service/src/main/resources/db/report-service-001.sql
> +IF NOT EXISTS(SELECT *
Tested the scripts locally by connecting to the Data Team sandbox RDS intance.

2023-11-02 19:05 UTC, alog-enquizit commented on report-service/src/main/resources/db/report-service-001.sql
> +IF OBJECT_ID(N'dbo.elr_raw', N'U') IS NULL
If table is absent then create else do nothing. Likewise for all tables.

2023-11-02 19:57 UTC, rshanmugam-enquizit requested changes
lgtm! can you wipe the INT1 database and run the liquibase `update` command and post the output back here? once the run is good, I'll approve this PR

2023-11-03 17:15 UTC, alog-enquizit commented
@rshanmugam-enquizit 
Synced with @ssathiah and found out that `NBS_DataIngest` database should be present before the liquibase table schemas can be created. 
As a result, we decided to create a sql script to manually create the `NBS_DataIngest` before running the `./gradlew update` which will trigger the liquibase schema update.

`IF NOT EXISTS(SELECT *
              FROM sys.databases
              WHERE name = 'NBS_DataIngest')
    BEGIN
        CREATE DATABASE NBS_DataIngest
    END
GO
USE NBS_DataIngest
GO`

I will retract this PR as a consequence of the above observation.

2023-11-03 18:33 UTC, rshanmugam-enquizit commented
> @rshanmugam-enquizit Synced with @ssathiah and found out that `NBS_DataIngest` database should be present before the liquibase table schemas can be created. As a result, we decided to create a sql script to manually create the `NBS_DataIngest` before running the `./gradlew update` which will trigger the liquibase schema update.
> 
> `IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'NBS_DataIngest') BEGIN CREATE DATABASE NBS_DataIngest END GO USE NBS_DataIngest GO`
> 
> I will retract this PR as a consequence of the above observation.

Interesting. We'll have the database already and we just need to make sure the tables are created only if it doesn't exist. So, we can just do that I believe right (take down create database but not the other?)

2023-11-03 21:01 UTC, alog-enquizit commented
Validated the scripts with @ssathiah  and @rshanmugam-enquizit in the dev and INT environments.

2023-11-03 21:17 UTC, rshanmugam-enquizit approved these changes
ship it!

2023-11-03 21:19 UTC, merged